"""hourly_rate va is_paid ustunlari qo'shildi

Revision ID: b51d7d87eea1
Revises: 1d01531e1048
Create Date: 2026-07-16 06:02:26.296009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51d7d87eea1'
down_revision = '1d01531e1048'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('hourly_rate', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hourly_rate')
    op.drop_column('shifts', 'is_paid')
    # ### end Alembic commands ###
