"""recurring_expenses jadvali qo'shildi

Revision ID: bf0862e3c674
Revises: b51d7d87eea1
Create Date: 2026-07-16 06:18:07.685758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0862e3c674'
down_revision = 'b51d7d87eea1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_generated_month', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_expenses_company_id'), 'recurring_expenses', ['company_id'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_id'), 'recurring_expenses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_expenses_id'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_company_id'), table_name='recurring_expenses')
    op.drop_table('recurring_expenses')
    # ### end Alembic commands ###
