"""sales jadvaliga customer_name va customer_phone qo'shildi

Revision ID: edd9d3d6b946
Revises: ce0e89afe397
Create Date: 2026-07-16 06:45:56.064822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd9d3d6b946'
down_revision = 'ce0e89afe397'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('customer_phone', sa.String(), nullable=True))
    op.create_index(op.f('ix_sales_customer_phone'), 'sales', ['customer_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_customer_phone'), table_name='sales')
    op.drop_column('sales', 'customer_phone')
    op.drop_column('sales', 'customer_name')
    # ### end Alembic commands ###
